# Generated by Django 4.2.3 on 2023-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
