# Generated by Django 4.2.3 on 2023-07-16 07:23

from django.db import migrations, models
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, upload_to=home.models.comic_directory_path),
        ),
        migrations.AddField(
            model_name='page',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
