# Generated by Django 4.2.3 on 2023-07-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='description',
            field=models.TextField(default='abc', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
