# Generated by Django 4.2.3 on 2023-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comic_description_comic_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
